### PR TITLE
added c++ code

### PR DESCRIPTION
**Pull request by reethikprasad**

### CODE REVIEW

**Comment by ashuprince121** [comment]
You need to add atleast 4 programs. You have added 1 add 3 more.

**Comment by reethikprasad** [comment]
Hi @ashuprince121 I have added the code

**Comment by ashuprince121** [comment]
Approved!

**Comment by reethikprasad** [comment]
@ashuprince121  can you add a label of hacktoberfest 
New rules are out there that maintainer of repo needs to opt in by adding a label of hacktoberfest 
Only those PR would be counted

**Comment by ashuprince121** [comment]
Thanks for letting me know , but there's still a issue, they also want every PR request's comment labeled as ‘hacktoberfest-accepted’.  For now I have added hacktober fest topic.

**Pull request merged**
