### PR TITLE
Prime Number.c

### PR DESCRIPTION
**Pull request by madihadongaonkar**
Program of Prime number in C

### CODE REVIEW

**Comment by ashuprince121** [comment]
Add atleast 4 programs , before making a PR.You have added 1 add 3 more programs.

**Comment by madihadongaonkar** [comment]
ok

**Comment by madihadongaonkar** [comment]
Added 4 Programs. will add more..
Accept my Pr please.

**Comment by ashuprince121** [comment]
Approved!

**Comment by madihadongaonkar** [comment]
i am new to github.. I don't know how to merge.

**Comment by madihadongaonkar** [comment]
Why i am still seeing my PR pending in hacktoberfest profile?

**Pull request merged**
